### ISSUE TITLE
Draw playbook

### ISSUE THREAD

**Issue by raffaelemancuso** [tacticalboard/tacticalboard#2]
Referring to basketball, would it be possible to implement drawing a full playbook?

I mean, not only players' positions, but also dribbles, passes, shoots, etc.

**Comment by hughplay** [comment]
That seems cool. Could you please give me an example image?

**Comment by raffaelemancuso** [comment]
![playbook](https://searx.tiekoetter.com/image_proxy?url=https%3A%2F%2Fcccdn-fe9e.kxcdn.com%2Fimages%2F53A.PNG&h=c753eedda41141c2089f556d06749d54f21feaebb1815f36c0c501d13e413306 "basketball play")

**Comment by hughplay** [comment]
![image](https://user-images.githubusercontent.com/30553791/158049485-e0344bdc-52a0-40a7-b296-995ec27e82db.png)

Now you can draw some lines. @raffaem
